SERVER_IP="192.168.42.110"
SERVER_HOSTNAME="server"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "2011.0"
  config.vagrant.plugins = "vagrant-reload"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048
  end

  config.vm.define SERVER_HOSTNAME do |server|
    server.vm.hostname = SERVER_HOSTNAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provision "shell",
      name: "Setting up mirrors and updating centos",
      inline:  <<-EOF
        set -e
        dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
        dnf -y update
        dnf -y group install "Development Tools"
        dnf -y install wget kernel-devel
      EOF
    server.vm.provision "shell",
      name: "Installing vbox guest additions",
      inline:  <<-EOF
        set -e
        uname -r
        wget http://download.virtualbox.org/virtualbox/6.1.34/VBoxGuestAdditions_6.1.34.iso
        mkdir /media/VBoxGuestAdditions
        mount -o loop,ro VBoxGuestAdditions_6.1.34.iso /media/VBoxGuestAdditions
        sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run --nox11
        rm VBoxGuestAdditions_6.1.34.iso
        umount /media/VBoxGuestAdditions
        rmdir /media/VBoxGuestAdditions
      EOF
    server.vm.provision :reload
    server.vm.provision "shell",  path: "scripts/install_k3s.sh", env: {"NODE_IP" => SERVER_IP}
    server.vm.synced_folder "./config", "/tt", type: "virtualbox"

  end

end
