SERVER_IP="192.168.42.110"
SERVER_HOSTNAME="server"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.box_version = "4.0.2"
  config.vagrant.plugins = "vagrant-reload"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 2048
  end

  config.vm.define SERVER_HOSTNAME do |server|
    server.vm.hostname = SERVER_HOSTNAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    server.vm.provision "shell",  path: "scripts/install_k3s.sh", env: {"NODE_IP" => SERVER_IP}

  end

end
