SERVER_IP="192.168.42.110"
SERVER_HOSTNAME="mkayumbaS"
AGENT_IP="192.168.42.111"
AGENT_HOSTNAME="mkayumbaSW"
K3S_TOKEN="my_super_secret_token"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.box_version = "4.0.2"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 512
  end
  
  config.vm.provision "shell",  path: "scripts/bootstrap_centos.sh"
  
  config.vm.define SERVER_HOSTNAME, primary: true do |server|
    server.vm.hostname = SERVER_HOSTNAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provision "shell",
      env: {"NODE_IP" => SERVER_IP, "AGENT_IP" => AGENT_IP, "AGENT_HOSTNAME" => AGENT_HOSTNAME, "TOKEN" => K3S_TOKEN},
      inline:  <<-EOF
        set -eu
        echo "$AGENT_IP $AGENT_HOSTNAME" >> /etc/hosts
        curl -sfL https://get.k3s.io | sh -s - server \
          --node-ip="${NODE_IP}" --token="${TOKEN}" --write-kubeconfig-mode 644
        echo "k3S node named $HOSTNAME installed with node ip $NODE_IP."  
      EOF
      
  end
    
  config.vm.define AGENT_HOSTNAME do |agent|
    agent.vm.hostname = AGENT_HOSTNAME
    agent.vm.network "private_network", ip: AGENT_IP
    agent.vm.provision "shell",
      env: {"NODE_IP" => AGENT_IP, "SERVER_IP" => SERVER_IP, "SERVER_HOSTNAME" => SERVER_HOSTNAME, "TOKEN" => K3S_TOKEN},
      inline:  <<-EOF
          set -eu
          echo "$SERVER_IP $SERVER_HOSTNAME" >> /etc/hosts
          curl -sfL https://get.k3s.io | sh -s - agent --server=https://"${SERVER_HOSTNAME}":6443 --node-ip="${NODE_IP}" --token="${TOKEN}"
          echo "k3S node named $HOSTNAME installed with node ip $NODE_IP."
      EOF
    
  end

end
